suborbital/docs

website/docs/atmo/getstarted/building-and-running.md
Closes #11 
Adds a blurb about what a successful test looks like.
=> Add successull request to atmo docs

website/docs/compute/quickstart/client-libraries/nodejs.md
Fulfilling link addition requested in Issue #42.
=> docs: add link to compute repo

website/docs/compute/quickstart/client-libraries/nodejs.md, website/docs/compute/quickstart/create-an-environment-token-with-subo.md
Made fixes requested in Issue #38.
=> docs: tidy up style issues from issue #38

README.md
=> Adding clarification to README

publish.sh, website/docusaurus.config.js
Testing deployment of PRs under their own respective paths on gh-pages
=> WIP Test updated publish script

website/docs/intro-to-webassembly/intro-to-wasm.md, website/sidebars.js
=> docs: add learning resource links

website/docs/atmo/runnable-api/request.md
=> Remove test tube icons from the first codeblock

website/docs/contributing/contributing-to-suborbital.md, website/sidebars.js
As requested in PR 93: https://github.com/suborbital/docs/pull/93#issuecomment-1078579469, for Issue #82.
=> docs: change main category url for contributing

website/docs/reactr/language-support.md
Creating a first draft of a language support table for Issue #67.
=> docs: create initial language support table

website/docs/atmo/usage/deploying-atmo.md
Closes #60 
Related to https://github.com/suborbital/atmo/pull/145
Do not merge until Atmo has been released with the above changeset
=> Add atmo tracing documentation

website/docs/reactr/wasm.md
=> docs: fix broken test data link

.github/workflows/links.yml
Add a link check to the docs workflow for Issue #87.
=> Create link checks for docs

website/docs/compute/quickstart/run-compute-locally.md
Clarified wording around starting a REPL to close Issue #41.
=> docs: change wording about starting REPL

website/docs/intro-to-webassembly/intro-to-wasm.md
=> docs: add a link to Lin's Wasm series

website/docs/reactr/language-support.md
Closes #139 
I hope that listing this as "Stable" is accurate!
@ospencer could you please confirm? Thank you!
=> Add `wat` format support

.github/workflows/accessibility.yml
* upgrades the action to fix an issue with the json interface returned.
* add white space trim for jwt storing.
* add stable working local action - ( remove `EXTERNAL` for local action usage )
=> chore(action): fix a11ywatch action remote api

website/docs/compute/cloud-deployment/configure-storage.md, website/sidebars.js
This PR adds documentation on how to configure bucket storage in Suborbital Compute.
=> feat: Add documentation on configuring bucket storage in Compute

website/docs/compute/cloud-deployment/configure-webhooks.md, website/sidebars.js
Adds overdue documentation for the recently released webhook feature for Compute.
=> feat: Add webhooks docs

.github/workflows/accessibility.yml
* update action to v1.12.0 fixing github action machine limits.
=> ci(accessibility): update a11ywatch action@1.12.0

website/docs/quickstart.md
Move the "Danger"/Compute -> SE2 notice to the relevant section of the quickstart.
=> move danger notice

CONTRIBUTING.md
=> fix: Correct contributing link

website/docs/hosted-quickstart.md, website/docs/how-to/deploy/cloud-deployment/install-se2-in-your-cloud-environment.md, website/docs/introduction.md, website/docs/open-source/atmo/runnable-api/sql-databases.md, website/docs/open-source/atmo/usage/deploying-atmo.md, website/docs/open-source/contributing-to-suborbital.md, website/docs/support.md, website/docusaurus.config.js
We still love Discord, but it's not as relevant for our current focus.
=> chore: Remove all mentions of Discord

website/docusaurus.config.js, website/package-lock.json, website/package.json
=> Integrate fathom analytics

README.md
=> Remove yarn documentation for this repo

website/docs/how-to/se2-js.md, website/docs/how-to/using-api.md
=> Remove mentions of yarn from the docs
